// This file was generated by Slater.app - Osmo Full Site

let paths = window.location.pathname.split('/')


// flow -> 
// flow has not been connected to a Webflow page.

// flow -> 

// flow has not been connected to a Webflow page.

// list -> 

// list has not been connected to a Webflow page.

// marketing-site -> 

// marketing-site has not been connected to a Webflow page.

// marketing-site.min -> 

// marketing-site.min has not been connected to a Webflow page.

// osmo-website-template -> 

// osmo-website-template has not been connected to a Webflow page.

// resource -> 

// resource has not been connected to a Webflow page.

// resource-ilja -> 

// resource-ilja has not been connected to a Webflow page.

// starter-kit -> 

// starter-kit has not been connected to a Webflow page.

// starter-kit-advanced -> 

// starter-kit-advanced has not been connected to a Webflow page.

// vault -> 

// vault has not been connected to a Webflow page.

// vault-backup -> 

// vault-backup has not been connected to a Webflow page.

// marketing-head -> 
// marketing-head has not been connected to a Webflow page.

// outseta-styling -> 
// outseta-styling has not been connected to a Webflow page.

// resource -> 
// resource has not been connected to a Webflow page.

// resource-ilja -> 
// resource-ilja has not been connected to a Webflow page.

// variables -> 
// variables has not been connected to a Webflow page.

// vault -> 
// vault has not been connected to a Webflow page.

