// This file was generated by Slater.app - resource.css


/* ------------------------- Hide Scrollbar -------------------------------------------------- */

body ::-webkit-scrollbar,
body::-webkit-scrollbar {display: none;} /* Chrome, Safari, Opera */
body {-ms-overflow-style: none;} /* IE & Edge */
html {scrollbar-width: none;} /* Firefox */

/* ------------------------- Reset -------------------------------------------------- */

*,
*:after,
*:before {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}

html {
  scroll-behavior: initial;
}

html,
body {
  -webkit-font-smoothing: antialiased;
}

svg {
  max-width: none;
  height: auto;
  box-sizing: border-box;
  vertical-align: middle;
}

/* ------------------------- Big Pixel Cursor ------------------------- */

/* Default cursor */
body.is--cursor,
body.is--cursor * {
  cursor: url("https://cdn.prod.website-files.com/6708f85ff3d3cba6aff436fb/671251b239d7aeb290a31ac5_cursor-default%402x.svg") 2 0, auto;
}

/* Text cursor */
body.is--cursor p,
body.is--cursor p span,
body.is--cursor h1,
body.is--cursor h2,
body.is--cursor h3,
body.is--cursor h4,
body.is--cursor h5,
body.is--cursor h6,
body.is--cursor input[type="text"],
body.is--cursor input[type="email"],
body.is--cursor textarea,
body.is--cursor [data-text] {
  cursor: url("https://cdn.prod.website-files.com/6708f85ff3d3cba6aff436fb/6714e4e1f367de40becf9029_cursor-text%402x.svg") 9 19, text;
}

/* Hover cursor */
body.is--cursor a,
body.is--cursor a *,
body.is--cursor a p,
body.is--cursor button,
body.is--cursor button *,
body.is--cursor input[type="submit"],
body.is--cursor input[type="submit"] *,
body.is--cursor input[type="button"],
body.is--cursor input[type="button"] *,
body.is--cursor [data-submit],
body.is--cursor [data-submit] *,
body.is--cursor [data-hover],
body.is--cursor [data-hover] *,
body.is--cursor [data-anchor-target],
body.is--cursor [data-vimeo-player-init],
body.is--cursor [data-vimeo-player-init] *,
body.is--cursor .vimeo-bg__btn,
body.is--cursor .vimeo-bg__btn *,
body.is--cursor input[type="radio"],
body.is--cursor input[type="checkbox"],
body.is--cursor select,
body.is--cursor .radiocheck-label,
body.is--cursor .flickity-arrow,
body.is--cursor .flickity-arrow *,
body.is--cursor .flickity-dot,
body.is--cursor [data-vimeo-lightbox-player],
body.is--cursor [data-vimeo-lightbox-player] * {
  cursor: url("https://cdn.prod.website-files.com/6708f85ff3d3cba6aff436fb/671251b212e6b71494aa67ff_cursor-pointer%402x.svg") 12 0, pointer;
}

